steps:
  # Step 1: Install dependencies and run tests
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/employee-api:$SHORT_SHA'
      - '.'

  # Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/employee-api:$SHORT_SHA'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'employee-api'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/employee-api:$SHORT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloudrun-repo/employee-api:$SHORT_SHA'
