steps:
  # Install dependencies and run tests
  - name: "python:3.12"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        pytest

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/project-a8be22b6-39b8-45b6-887/app1/employee-api:$SHORT_SHA"
      - "."

  # Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/project-a8be22b6-39b8-45b6-887/app1/employee-api:$SHORT_SHA"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "employee-api"
      - "--image=us-central1-docker.pkg.dev/project-a8be22b6-39b8-45b6-887/app1/employee-api:$SHORT_SHA"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "us-central1-docker.pkg.dev/project-a8be22b6-39b8-45b6-887/app1/employee-api:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
