steps:
  # Run tests
  - name: "python:3.12"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install -r requirements.txt
        export PYTHONPATH=$PWD
        python -m pytest tests/

  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/employee-api:latest"
      - "."

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/employee-api:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "employee-api"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/app1/employee-api:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/app1/employee-api:latest"

options:
  logging: CLOUD_LOGGING_ONLY
